<script setup>
import { Link } from '@inertiajs/vue3';
</script>

<template>
    <div class="border-b border-gray-200 dark:border-gray-700 mb-6">
        <nav class="-mb-px flex flex-wrap gap-x-6 gap-y-1">
            <Link :href="route('settings.legal-entities.index')" :class="[route().current('settings.legal-entities.index') ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:text-gray-400 dark:hover:text-gray-300 dark:hover:border-gray-600', 'inline-flex items-center gap-1.5 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors']"><i class="ri-bank-line"></i> Юридические лица</Link>
            <Link :href="route('settings.branches.index')" :class="[route().current('settings.branches.index') ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:text-gray-400 dark:hover:text-gray-300 dark:hover:border-gray-600', 'inline-flex items-center gap-1.5 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors']"><i class="ri-store-2-line"></i> Локации</Link>
            <Link :href="route('settings.business-directions.index')" :class="[route().current('settings.business-directions.index') ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:text-gray-400 dark:hover:text-gray-300 dark:hover:border-gray-600', 'inline-flex items-center gap-1.5 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors']"><i class="ri-compass-3-line"></i> Направления</Link>
            <Link :href="route('settings.posts.index')" :class="[route().current('settings.posts.index') ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:text-gray-400 dark:hover:text-gray-300 dark:hover:border-gray-600', 'inline-flex items-center gap-1.5 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors']"><i class="ri-car-washing-line"></i> Посты</Link>
            <Link :href="route('settings.warehouse.index')" :class="[route().current('settings.warehouse.index') ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:text-gray-400 dark:hover:text-gray-300 dark:hover:border-gray-600', 'inline-flex items-center gap-1.5 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors']"><i class="ri-archive-2-line"></i> Склад</Link>
            <Link :href="route('settings.custom-fields.index')" :class="[route().current('settings.custom-fields.index') ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:text-gray-400 dark:hover:text-gray-300 dark:hover:border-gray-600', 'inline-flex items-center gap-1.5 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors']"><i class="ri-input-method-line"></i> Кастомные поля</Link>
            <Link :href="route('settings.roles-permissions.index')" :class="[route().current('settings.roles-permissions.index') ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:text-gray-400 dark:hover:text-gray-300 dark:hover:border-gray-600', 'inline-flex items-center gap-1.5 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors']"><i class="ri-shield-user-line"></i> Роли и Права</Link>
            <Link :href="route('settings.crm.index')" :class="[route().current('settings.crm.index') ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:text-gray-400 dark:hover:text-gray-300 dark:hover:border-gray-600', 'inline-flex items-center gap-1.5 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors']"><i class="ri-user-3-line"></i> Клиенты и Авто</Link>
            <Link :href="route('settings.loyalty.index')" :class="[route().current('settings.loyalty.index') ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:text-gray-400 dark:hover:text-gray-300 dark:hover:border-gray-600', 'inline-flex items-center gap-1.5 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors']"><i class="ri-vip-crown-2-line"></i> Система лояльности</Link>
            <Link :href="route('settings.pipelines.index')" :class="[route().current('settings.pipelines.*') ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:text-gray-400 dark:hover:text-gray-300 dark:hover:border-gray-600', 'inline-flex items-center gap-1.5 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors']"><i class="ri-funds-line"></i> Воронки</Link>
            <Link :href="route('settings.payroll.index')" :class="[route().current('settings.payroll.index') ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:text-gray-400 dark:hover:text-gray-300 dark:hover:border-gray-600', 'inline-flex items-center gap-1.5 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors']"><i class="ri-money-dollar-circle-line"></i> Зарплата</Link>
            <Link :href="route('settings.channels.index')" :class="[route().current('settings.channels.index') ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:text-gray-400 dark:hover:text-gray-300 dark:hover:border-gray-600', 'inline-flex items-center gap-1.5 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors']"><i class="ri-chat-3-line"></i> Каналы связи</Link>
            <Link :href="route('settings.message-templates.index')" :class="[route().current('settings.message-templates.index') ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:text-gray-400 dark:hover:text-gray-300 dark:hover:border-gray-600', 'inline-flex items-center gap-1.5 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors']"><i class="ri-message-2-line"></i> Шаблоны сообщений</Link>
            <Link :href="route('settings.document-templates.index')" :class="[route().current('settings.document-templates.index') ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:text-gray-400 dark:hover:text-gray-300 dark:hover:border-gray-600', 'inline-flex items-center gap-1.5 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors']"><i class="ri-file-text-line"></i> Шаблоны документов</Link>
        </nav>
    </div>
</template>
